// Configuration constants for Thoughts component
export const THOUGHT_CONFIG = {
  INITIAL_BATCH_SIZE: 12,
  BATCH_SIZE: 12,
  LOADING_DELAY_MS: 300,
  ANIMATION_TYPES: 3,
  ANIMATION_DELAY_MULTIPLIER: 0.5,
  INTERSECTION_THRESHOLD: 0.1,
  // Positioning constants
  MIN_LEFT_PERCENT: 2,
  MAX_LEFT_PERCENT: 85,
  MIN_TOP_PERCENT: 10,
  MAX_TOP_PERCENT: 80,
  BASE_LEFT_OFFSET: 5,
  BASE_TOP_OFFSET: 15,
  HORIZONTAL_SPREAD: 90,
  VERTICAL_SPREAD: 70,
  VARIATION_RANGE: 20,
  VARIATION_OFFSET: 10,
  // Container height constants
  MIN_CONTAINER_HEIGHT: 600,
  BASE_HEIGHT: 200,
  HEIGHT_PER_ROW: 200,
  CARDS_PER_ROW: 3,
  CONTAINER_PADDING_BOTTOM: 100,
  // Observer target positioning
  OBSERVER_BOTTOM_OFFSET: 20,
  OBSERVER_HEIGHT: 80,
};

